config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'

  root "checklists#new"

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  get    'explore'   => 'checklists#index'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post   'checkings' => 'checkings#create'
  delete 'checkings' => 'checkings#destroy'

  resources :users do
    member do
      get 'checklists'
    end
  end
  resources :checklists do
    member do
      get 'clone'
      get 'new_secret_key'
    end
  end
  resources :checkings
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :checklists, dependent: :destroy
  has_many :checkings, dependent: :destroy

  before_save { email.downcase! }
  validates :email, presence:   true,
                    format:     { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :only_owner, only: [:checklists]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if verify_recaptcha(:model => @user, :message => "Oh! It's error with reCAPTCHA!") && @user.save
      log_in @user
      flash[:info] = "User added"
      redirect_to checklists_user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "User updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def checklists
    @checklists = Checklist.where(:user_id => params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def only_owner
      user = User.find(params[:id])
      if !logged_in? or current_user.id != user.id
        flash[:warning] = 'You are not authorized to see this page.'
        redirect_to root_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/checklists.html.erb
<% provide(:title, 'Your checklists') %>
<h1>Your checklists</h1>

<% if @checklists.any? %>
    <ul>
        <% @checklists.each do |checklist| %>
          <% if checklist.Link? %>
              <li><%= link_to checklist.title, checklist_path(:id => checklist.id, :key => checklist.secret_key) %></li>
          <% else %>
              <li><%= link_to checklist.title, checklist %></li>
          <% end %>
        <% end %>
    </ul>
<% else %>
    <p>
      It seems that you do not have any checklists yet. What about
      <%= link_to 'creating one', new_checklist_path %>?
    </p>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Update your account') %>
<h1>Update your account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'error_messages' %>

        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <div class="text-center">
          <%= f.submit "Save changes", class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Create new account') %>
<h1>Create new account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'error_messages' %>

        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= recaptcha_tags %>
        </div>

        <div class="text-center">
          <%= f.submit "Create new account", class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>