config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'

  root "checklists#new"

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  get    'explore'   => 'checklists#index'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post   'checkings' => 'checkings#create'
  delete 'checkings' => 'checkings#destroy'

  resources :users do
    member do
      get 'checklists'
    end
  end
  resources :checklists do
    member do
      get 'clone'
      get 'new_secret_key'
    end
  end
  resources :checkings
end

app/models/checklist.rb
require 'securerandom'

class Checklist < ActiveRecord::Base
  belongs_to :user
  has_many :emails, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :items, :through => :categories

  accepts_nested_attributes_for :categories,
                                :allow_destroy => true
  accepts_nested_attributes_for :emails,
                                :allow_destroy => true

  before_validation do 
    errors.add(:cooperation,  "must be unchecked for Public sharing") if Public? and cooperation?
  end
  before_create { self.secret_key = SecureRandom.hex }
  enum sharing: [ :Public, :Private, :Link ]
  validates :title, presence: true, length: { minimum: 3, maximum: 255 }
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :validate_secret_key, only: [:show]
  before_action :validate_private_checklist, only: [:show]
  before_action :validate_ownership, only: [:edit, :update, :destroy]
  before_action :validate_logged_in, only: [:clone]

  def index
    @checklists = Checklist.Public
  end

  def show
    @checklist = Checklist.includes(categories: [:items => [:checkings]]).find(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  def new
    @checklist = Checklist.new
    @checklist.emails.build
    category = @checklist.categories.build
    item = category.items.build
    item.build_automatic_location_is_http
    item.build_automatic_travis_is_green
    item.build_automatic_coverage_over
  end

  def edit
    @checklist = Checklist.includes(:emails, categories: [items: :automatic_location_is_http]).find(params[:id])

    # build at least one category if it does not exist
    if @checklist.categories.empty?
      category = @checklist.categories.build
      category.items.build
    end

    @checklist.categories.each do |category|
      category.items.each do |item|
        item.build_automatic_location_is_http if item.automatic_location_is_http.nil?
        item.build_automatic_travis_is_green if item.automatic_travis_is_green.nil?
        item.build_automatic_coverage_over if item.automatic_coverage_over.nil?
      end
    end

    # reform emails
    emails = []
    @checklist.emails.each do |e|
      emails << e.email
    end
    @checklist.emails.clear # TODO: find a way not to delete it from DB, just from this collection
    @checklist.emails.build(:email => emails.join("\n"))
  end

  def create
    # remove all items that have no title
    params['checklist']['categories_attributes'].each do |key, category|
      category['items_attributes'].delete_if do |key, item|
        item['title'].strip.empty? ? true : false
      end
    end

    # remove all categories that are left empty
    params['checklist']['categories_attributes'].delete_if do |key, category|
      category['items_attributes'].empty? ? true : false
    end

    # divide emails
    emails = []
    if defined? params['checklist']['emails_attributes']['0']
      params['checklist']['emails_attributes']['0']['email'].split("\n").each do |email|
        emails << {:email => email.strip} if email.strip.length > 0
      end
    end
    params['checklist']['emails_attributes'] = emails

    # filter automatic items
    params['checklist']['categories_attributes'].each do |key, category|
      category['items_attributes'].each do |key, item|
        item.delete :automatic_location_is_http_attributes if item['automatic'] != 'location_is_https'
        item.delete :automatic_travis_is_green_attributes if item['automatic'] != 'travis_is_green'
        item.delete :automatic_coverage_over_attributes if item['automatic'] != 'coverage_over'
      end
    end

    if logged_in?
      @checklist = current_user.checklists.build(checklist_params)
    else
      @checklist = Checklist.new(checklist_params)
    end
    if @checklist.save
      flash[:info] = "Checklist added."
      flash[:info] += ' You can log in to gain ownership of this checklist. You will be able to edit and delete it afterwards' if !logged_in?

      if !logged_in?
        cookies['checklist-' + @checklist.id.to_s] = @checklist.secret_key
      end

      redirect_to checklist_path(:id => @checklist.id, :key => @checklist.secret_key) and return if @checklist.Link?
      redirect_to @checklist
    else
      # recreate at least one category
      if @checklist.categories.empty?
        category = @checklist.categories.build
        category.items.build
      end

      # bind emails together
      @checklist.emails.clear
      @checklist.emails.build(:email => emails.map{|val| val.map{|key, value| value}}.join("\n"))

      render 'new'
    end
  end

  def update
    # remove all items that have no title
    params['checklist']['categories_attributes'].each do |key, category|
      category['items_attributes'].delete_if do |key, item|
        item['title'].strip.empty? ? true : false
      end
    end

    # remove all categories that are left empty
    params['checklist']['categories_attributes'].delete_if do |key, category|
      category['items_attributes'].empty? ? true : false
    end

    # divide emails
    emails = []
    params['checklist']['emails_attributes']['0']['email'].split("\n").each do |email|
      emails << {:email => email.strip} if email.strip.length > 0
    end
    params['checklist']['emails_attributes'] = emails

    # filter automatic items
    params['checklist']['categories_attributes'].each do |key, category|
      category['items_attributes'].each do |key, item|
        item.delete :automatic_location_is_http_attributes if item['automatic'] != 'location_is_https'
        item.delete :automatic_travis_is_green_attributes if item['automatic'] != 'travis_is_green'
        item.delete :automatic_coverage_over_attributes if item['automatic'] != 'coverage_over'
      end
    end

    @checklist = Checklist.find(params[:id])
    if @checklist.update_attributes(checklist_params)
      flash[:info] = "Checklist updated"
      redirect_to checklist_path(:id => @checklist.id, :key => @checklist.secret_key) and return if @checklist.Link?
      redirect_to @checklist
    else
      # recreate at least one category
      if @checklist.categories.empty?
        category = @checklist.categories.build
        category.items.build
      end

      # bind emails together
      @checklist.emails.clear
      @checklist.emails.build(:email => emails.map{|val| val.map{|key, value| value}}.join("\n"))

      render 'new'
    end
  end

  def destroy
    if Checklist.find(params[:id]).destroy
      flash[:info] = "Checklist deleted"
      redirect_to root_path
    end
  end

  def clone
    @checklist = Checklist.find(params[:id])
    new_checklist = @checklist.deep_clone include: {
      :categories => {:items => [
          :automatic_location_is_http,
          :automatic_travis_is_green,
          :automatic_coverage_over
      ]}
    }, validate: false
    if new_checklist.save
      flash[:info] = "Checklist cloned"
      redirect_to checklist_path(:id => new_checklist.id, :key => new_checklist.secret_key) and return if new_checklist.Link?
      redirect_to new_checklist
    else
      flash[:info] = "Unable to clone checklist"
      render 'show'
    end
  end

  def new_secret_key
    require 'securerandom'

    hash = SecureRandom.hex
    checklist = Checklist.find(params[:id]).update(:secret_key => hash)
    flash[:info] = "Secure key updated. See new link below the checklist"
    redirect_to checklist_path(:key => hash)
  end

  private

    def checklist_params
      params.require(:checklist).permit(:title, :sharing,
        categories_attributes: [:id, :title, :_destroy,
          items_attributes: [:id, :title, :link, :description, :optional, :automatic, :_destroy,
            automatic_location_is_http_attributes: [:id, :urls],
            automatic_travis_is_green_attributes: [:id, :repo],
            automatic_coverage_over_attributes: [:id, :repo, :percentage]
          ]
        ],
        emails_attributes: [:email]
      )
    end

    def validate_secret_key
      checklist = Checklist.find(params[:id])
      if checklist.Link? and checklist.secret_key != params[:key]
        flash[:warning] = "Wrong secret key"
        redirect_to root_path
      end
    end

    def validate_private_checklist
      checklist = Checklist.includes(:emails).find(params[:id])
      if checklist.Private?
        if !logged_in? or (checklist.user_id != current_user.id and !checklist.emails.exists?(:email => current_user.email))
          flash[:warning] = "You are not authorized to see this checklist!"
          redirect_to root_path
        end
      end
    end

    def validate_ownership
      checklist = Checklist.find(params[:id])
      if !logged_in? or checklist.user_id != current_user.id
        flash[:warning] = 'You are not authorized to edit this checklist.'
        redirect_to root_path
      end
    end

    def validate_logged_in
      if !logged_in?
        flash[:warning] = 'You must be logged in to do this.'
        redirect_to root_path
      end
    end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
  def permission_description(sharing)
    case sharing
      when 'Public'
        return 'Checklist will be visible to everyone. Anyone can clone it and use it. It will be listed in Explore page as well.'
      when 'Private'
        return 'Checklist will be accessible only by users whose email you specify below and you.'
      when 'Link'
        return 'Checklist will be accessible by anyone with specific link. You decide, to with whom you share the link. Also, you can generate new link whenever you want.'
    end
  end
end

app/views/checklists/_categories_fields.html.erb
<div class="category">
  <div class="category-title-wrapper">
    <%= f.text_field :title, placeholder: 'Category title...', class: 'category-title' %>
    <div class="icons">
      <%= fa_icon "trash-o", title: 'Remove category', class: "fa-fw category-delete" %>
    </div>
  </div>

  <%= f.fields_for :items do |builder| %>
      <%= render 'items_fields', :f => builder %>
  <% end %>

  <%= f.hidden_field :_destroy, class: 'category-destroy' %>

</div>

app/views/checklists/_form.html.erb
<%= form_for(@checklist, :html => {:autocomplete => "off"}) do |c| %>
    <% if @checklist.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h3>
            <%= pluralize(@checklist.errors.count, "error") %> prohibited
            this checklist from being saved:
          </h3>

          <ul>
            <% @checklist.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= c.text_field :title, placeholder: 'Checklist title...', class: 'checklist-title' %>

    <div class="checklist">
      <%= c.fields_for :categories do |builder| %>
          <%= render "categories_fields", :f => builder %>
      <% end %>
    </div>

    <div class="checklist-permissions">
      <h4>Choose permissions for this checklist</h4>
      <% Checklist.sharings.keys.each do |sharing| %>
          <%# Private checklist can only be created by logged in users. The problem is, that he would never
                be able to access his own checklist, since he cannot access it directly after creating it,
                 and thus he cannot claim ownership of it. %>
          <% if sharing != 'Private' or logged_in? %>
              <div class="sharing-<%= sharing %>">
                  <%= c.radio_button :sharing, sharing %>
                  <%= c.label "sharing_#{sharing.downcase}", sharing, title: permission_description(sharing) %>

                    <% if sharing == 'Private' %>
                        <div>
                          <%= c.fields_for :emails do |builder| %>
                              <%= builder.text_area :email, class: 'form-control', placeholder: 'Insert every email, whose account will have access to this checklist. One email per line.' %>
                          <% end %>
                        </div>
                    <% end %>
              </div>
          <% end %>
      <% end %>
    </div>

    <div class="text-center">
        <%= c.submit "Submit", class: 'btn btn-primary' %>
        <% if @checklist.persisted? %>
            or
            <%= link_to 'cancel', @checklist %>
        <% end %>
    </div>
<% end %>

<script>
    $(function(){
        var edit = <%= @checklist.persisted? ? 'true' : 'false' %>;

        function category_template(id) {
            var item = item_template(0, id);

            return `<div class="category">
            <div class="category-title-wrapper">
            <input type="text" id="checklist_categories_attributes_${id}_title" name="checklist[categories_attributes][${id}][title]" class="category-title" placeholder="Category title...">
            <div class="icons">
            <i class="fa fa-trash-o fa-fw category-delete" title="Remove category"></i>
            </div>
            </div>

                ${item}
            </div>`
        }

        function item_template(id, cat_id) {
            return `<div class="item">
            <input type="checkbox" disabled="">
            <input type="text" id="checklist_categories_attributes_${cat_id}_items_attributes_${id}_title" name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][title]" class="item-title" placeholder="Item title...">
            <div class="icons">
            <i class="fa fa-magic fa-fw item-automatic" title="Automatic?"></i><i class="fa fa-pencil fa-fw item-details" title="Details"></i><i class="fa fa-trash-o fa-fw item-delete" title="Remove item"></i>
            </div>

            <div class="modal details-modal">
            <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
            <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title">Item details</h4>
            </div>
            <div class="modal-body">
            <textarea id="checklist_categories_attributes_${cat_id}_items_attributes_${id}_description" name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][description]" class="form-control" placeholder="Insert item description in markdown"></textarea>
            </div>
            <div class="modal-footer">
            <button data-dismiss="modal" class="btn btn-primary" type="button">Save changes</button>
            </div>
            </div>
            </div>
            </div>

            <div class="modal automatic-modal">
            <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Choose a type of automatic item</h4>
            </div>
            <div class="modal-body">
            <ul class="automatic-items-list">
            <li>
            <input type="radio" name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][automatic]" id="checklist_categories_attributes_${cat_id}_items_attributes_${id}_automatic_none" checked="checked" value="no"> <label for="checklist_categories_attributes_${cat_id}_items_attributes_${id}_automatic_none">none</label>
            </li>
            <li>
            <input type="radio" name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][automatic]" id="checklist_categories_attributes_${cat_id}_items_attributes_${id}_automatic_location_is_https" value="location_is_https"> <label for="checklist_categories_attributes_${cat_id}_items_attributes_${id}_automatic_location_is_https" title="Item will be checked automatically after all URLs specified below will redirect to https.">Location is HTTPS-only</label>

            <div>
            <textarea name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][automatic_location_is_http_attributes][urls]" class="form-control" placeholder="Please, specify all URLs that must force-redirect to HTTPS to check this item. One URL per line."></textarea>
            </div>
            </li>
            <li>
            <input type="radio" name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][automatic]" id="checklist_categories_attributes_${cat_id}_items_attributes_${id}_automatic_travis_is_green" value="travis_is_green"> <label for="checklist_categories_attributes_${cat_id}_items_attributes_${id}_automatic_travis_is_green" title="Item will be checked automatically after repository specified below passes every test on every enviroment at travis-ci.org.">Travis is green</label>

            <div>
            <input name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][automatic_travis_is_green_attributes][repo]" class="form-control" placeholder="Please, specify repository address. Eg. \"rails/rails\".">
            </div>
            </li>
            <li>
            <input type="radio" name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][automatic]" id="checklist_categories_attributes_${cat_id}_items_attributes_${id}_automatic_coverage_over" value="coverage_over"> <label for="checklist_categories_attributes_${cat_id}_items_attributes_${id}_automatic_coverage_over" title="Item will be checked automatically after github repository specified below exceeds test coverage percentage specified below at coveralls.io.">Code coverage over</label>

            <div>
            <input name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][automatic_coverage_over_attributes][repo]" class="form-control" placeholder="Please, specify repository address. Eg. rails/rails">
            <input name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][automatic_coverage_over_attributes][percentage]" type="number" min="0" max="100" class="form-control" placeholder="Coverage percentage">
            </div>
            </li>
            </ul>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Save changes</button>
            </div>
            </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->

            <div class="hidden">
            Item link: <input type="url" id="checklist_categories_attributes_${id}_items_attributes_${id}_link" name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][link]">
            <input type="checkbox" id="checklist_categories_attributes_${cat_id}_items_attributes_${id}_optional" name="checklist[categories_attributes][${cat_id}][items_attributes][${id}][optional]" value="1"> Optional?
            </div>
            </div>`
        }

        $(document).on('keyup', '.category:last .category-title', function(){
            if($(this).val() !== '') {
                // find out category id
                var id = parseInt($(this).attr('name').replace(/[^0-9]*([0-9]+)[^0-9]*/, '$1'));
                $('.category:last').after(category_template(id + 1));
            }
        });

        $(document).on('keyup', '.item:last-of-type .item-title', function(){
            if($(this).val() !== '') {
                // find out category id and item id
                var cat_id = parseInt($(this).attr('name').replace(/[^0-9]*([0-9]+)[^0-9]*[0-9]+/, '$1'));
                var id = parseInt($(this).attr('name').replace(/[^0-9]*[0-9]+[^0-9]*([0-9]+)/, '$1'));
                $(this).parent().after(item_template(id + 1, cat_id));
            }
        });

        // generate empty category and item per category to allow adding new categories and items when editing
        $('input').trigger('keyup');

        $(document).on('click', '.category-delete', function(){
            if($('.category').length > 1) {
                if(edit) {
                    $(this).parents('.category')
                        .hide()
                        .children('.category-destroy').val('true')
                }
                else {
                    $(this).parent().parent().parent().remove();
                }
            }
        });

        $(document).on('click', '.item-delete', function(){
            if($(this).parent().parent().siblings('.item').length > 0) {
                if(edit) {
                    $(this).parents('.item')
                        .hide()
                        .find('.item-destroy').val('true')
                }
                else {
                    $(this).parent().parent().remove();
                }
            }
        });

        $(document).on('click', '.item-details', function(){
            $(this).parent().siblings('.details-modal').modal()
        });

        $(document).on('hide.bs.modal', '.details-modal', function(){
            var icon = $(this).siblings('.icons').children('.item-details');

            if($(this).find('textarea').val() != '') {
                icon.addClass('filled');
            }
            else {
                icon.removeClass('filled')
            }
        });

        $(document).on('hide.bs.modal', '.automatic-modal', function(){
            var icon = $(this).siblings('.icons').children('.item-automatic');

            if($(this).find('.automatic-items-list li:first input').is(':checked')) {
                icon.removeClass('filled')
            }
            else {
                icon.addClass('filled');
            }
        });

        $(document).on('keydown', '.modal.in textarea', function(e){
            if(e.ctrlKey && e.keyCode == 13) {
                $('.modal.in').modal('hide');
            }
        });


        $(document).on('click', '.item-automatic', function(){
            $(this).parent().siblings('.automatic-modal').modal()
        });

    })
</script>

app/views/checklists/_items_fields.html.erb
<div class="item">
    <input type="checkbox" disabled>
    <%= f.text_field :title, placeholder: 'Item title...', class: 'item-title' %>
    <div class="icons">
      <%= fa_icon "magic", title: 'Automatic?', class: "fa-fw item-automatic #{'filled' unless f.object.no? if f.object.persisted?}" %><%= fa_icon "pencil", title: 'Details', class: "fa-fw item-details #{'filled' unless f.object.description.empty? if f.object.persisted?}" %><%= fa_icon "trash-o", title: 'Remove item', class: "fa-fw item-delete" %>
    </div>

    <div class="modal details-modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Item details</h4>
          </div>
          <div class="modal-body">
            <%= f.text_area :description, placeholder: 'Insert item description in markdown', class: 'form-control' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal automatic-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Choose a type of automatic item</h4>
        </div>
        <div class="modal-body">
          <ul class="automatic-items-list">
            <li>
              <%= f.radio_button :automatic, :no %>
              <%= f.label :automatic_no, 'None' %>
            </li>
            <li>
              <%= f.radio_button :automatic, :location_is_https %>
              <%= f.label :automatic_location_is_https, 'Location is HTTPS-only', title: 'Item will be checked automatically after all URLs specified below will redirect to https.' %>

              <div>
                <%= f.fields_for :automatic_location_is_http do |c| %>
                    <%= c.text_area :urls, class: 'form-control', placeholder: 'Please, specify all URLs that must force-redirect to HTTPS to check this item. One URL per line.' %>
                <% end %>
              </div>
            </li>
            <li>
              <%= f.radio_button :automatic, :travis_is_green %>
              <%= f.label :automatic_travis_is_green, 'Travis is green', title: 'Item will be checked automatically after repository specified below passes every test on every enviroment at travis-ci.org.' %>

              <div>
                <%= f.fields_for :automatic_travis_is_green do |c| %>
                    <%= c.text_field :repo, class: 'form-control', placeholder: 'Please, specify repository address. Eg. "rails/rails"' %>
                <% end %>
              </div>
            </li>
            <li>
              <%= f.radio_button :automatic, :coverage_over %>
              <%= f.label :automatic_coverage_over, 'Code coverage over', title: 'Item will be checked automatically after github repository specified below exceeds test coverage percentage specified below at coveralls.io.' %>

              <div>
                <%= f.fields_for :automatic_coverage_over do |c| %>
                    <%= c.text_field :repo, class: 'form-control', placeholder: 'Please, specify repository address. Eg. rails/rails' %>
                    <%= c.number_field :percentage, class: 'form-control', placeholder: 'Coverage percentage', min: 0, max: 100 %>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" data-dismiss="modal">Save changes</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div class="hidden">
      Item link: <%= f.url_field :link %>
      <%= f.check_box :optional, include_hidden: false %> Optional?
      <%= f.hidden_field :_destroy, class: 'item-destroy' %>
    </div>
</div>

app/views/checklists/edit.html.erb
<% provide(:title, "Edit checklist #{@checklist.title}") %>
<%= render 'form' %>

app/views/checklists/show.html.erb
<% provide(:title, @checklist.title) %>
<h1 class="checklist-title"><%= @checklist.title %></h1>

<div class="checklist">
    <% @checklist.categories.each do |category| %>
      <div class="category">
        <h2 class="category-title"><%= category.title %></h2>
        <ul class="category-list">
            <% category.items.each do |item| %>
              <li>
                <%= check_box_tag(item.id, 1, (item.checkings.find_by(user_id: nil).present? or item.checkings.find_by(user_id: current_user).present?), disabled: !item.no?, title: !item.no? ? 'This item is automatic - it will check automatically after requirements given are met.' : '') %>
                <%= label_tag(item.id, item.title) %>
                <% if item.description.length > 0 %>
                    <%= fa_icon "arrow-down", class: "fa-fw show-description" %>
                    <div class="description">
                      <%== @markdown.render(item.description) %>
                    </div>
                <% end %>
              </li>
            <% end %>
        </ul>
      </div>
    <% end %>
</div>

<p>
  <%= link_to fa_icon("external-link", title: 'Clone checklist', class: "fa-fw"), clone_checklist_path if logged_in? %>
  <%= link_to fa_icon("pencil", title: 'Edit checklist', class: "fa-fw"), edit_checklist_path if logged_in? and @checklist.user_id == current_user.id %>
  <%= link_to fa_icon("trash-o", title: 'Delete checklist', class: "fa-fw"), @checklist, :method => :delete, :confirm => "You sure?",
              :title => "Delete" if logged_in? and @checklist.user_id == current_user.id %>
  <%= link_to 'RESET', '#', id: 'reset-checklist', style: ('float: right' if logged_in?) %>
</p>

<% if @checklist.Link? %>
    <p>This checklist can only be accessed by special link provided here:</p>
    <code><%= "#{checklist_url}?key=#{@checklist.secret_key}" %></code>
    <p><%= link_to 'Generate new link?', new_secret_key_checklist_path %></p>
<% end %>

<script>
  $(function(){
      set_checkboxes();
      // ensure all currently opened windows get updated
      $(window).on('storage', set_checkboxes);

      $(document).on('click', '#reset-checklist', function(e){
          $('input[type=checkbox]').each(function(){
              $(this).prop('checked', false);
              localStorage.removeItem('checklists-' + this.id);
          });

          e.preventDefault();
      });

      $(document).on('change', 'input', function(){
          if(localStorage['checklists-' + this.id]) {
              localStorage.removeItem('checklists-' + this.id);
          }
          else {
              localStorage.setItem('checklists-' + this.id, Date.now());
          }
      });

      function set_checkboxes(){
          // ensure no checkbox is checked (except for automatic ones)
          $('input[type=checkbox]:enabled').prop('checked', false);
          // check only checkboxes stored in local storage
          for(item in localStorage) {
              $('#' + item.replace('checklists-', '')).prop('checked', true)
          }
      }

      /*
      $(document).on('change', 'input', function(e){
          var self = this;

          if(self.checked) { // was not checked, so we need to create a checking
              self.checked = false; // uncheck it until we are confirmed that checking was created

              $.ajax({
                  url: '<%= checkings_path(:format => :json) %>',
                  method: 'post',
                  data: {
                      'item_id': self.id
                  }
              })
              .done(function(data){
                if(data.result) {
                    self.checked = true;
                }
              })
          }
          else { // was checked, needs to delete record from database
              self.checked = true; // check it until we are confirmed that checking was deleted

              $.ajax({
                  url: '<%= checkings_path(:format => :json) %>',
                  method: 'post',
                  data: {
                      '_method': 'delete',
                      item_id: self.id
                  }
              })
              .done(function(data){
                  if(data.result) {
                      self.checked = false;
                  }
              })
          }
      });
      */

      $(document).on('click', '.show-description', function(){
         $(this).siblings('.description').toggle();
      });

  })
</script>