config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'

  root "checklists#new"

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  get    'explore'   => 'checklists#index'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post   'checkings' => 'checkings#create'
  delete 'checkings' => 'checkings#destroy'

  resources :users do
    member do
      get 'checklists'
    end
  end
  resources :checklists do
    member do
      get 'clone'
      get 'new_secret_key'
    end
  end
  resources :checkings
end

app/views/layouts/_footer.html.erb
<!--<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>-->

<script type="text/javascript" charset="utf-8">
    var regexp = new RegExp("(?:^delete_local_checkings|;\s*delete_local_checkings)=(.*?)(?:;|$)", "g");
    var result = regexp.exec(document.cookie);
    result = (result === null) ? null : result[1];
    if(result) {
        for(item in localStorage) {
            localStorage.removeItem(item);
        }

        document.cookie = "delete_local_checkings=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/"
    }
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New checklist", root_path %></li>
        <li><%= link_to "Explore", explore_path %></li>
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Your checklists", checklists_user_path(current_user) %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>

</div>
</body>
</html>